# Generated by Django 6.1 on 2026-09-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(max_length=100, unique=True)),
                ('dieta', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=150)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('raro', 'Raro'), ('lendario', 'Lendário')], default='comum', max_length=10)),
                ('pontos_xp', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='FigurinhaCapturada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_base64', models.TextField()),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'especie')},
            },
        ),
    ]
